/* Generated By:JavaCC: Do not edit this line. BAJParserConstants.java */
/**
 * AVERTISSEMENT : Ces fichiers sont générés de manière automatique par JavaCC
 * à partir du fichier BAJParser.jj
 */

package jeu.shazamm.parser;

public interface BAJParserConstants {

  int EOF = 0;
  int EOL = 1;
  int TWOEOLS = 2;
  int NOT_EOL = 3;
  int kwCoupManche = 5;
  int kwCoupTour = 6;
  int kwBilanMise = 7;
  int kwMise = 8;
  int kwSorts = 9;
  int kwClonage = 10;
  int kwDestruction = 11;
  int kwVol = 12;
  int kwRecyclage = 13;
  int kwLienPartie = 14;
  int kwRefPartie = 15;
  int kwDernierResultats = 16;
  int idMise = 19;
  int idJoueur = 20;
  int idSort = 21;
  int idClone = 22;
  int idVol = 23;
  int idRec = 24;
  int END_TR = 25;
  int kwmVol = 26;
  int NUM = 28;

  int DEFAULT = 0;
  int MISE = 1;
  int NUM_INT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<TWOEOLS>",
    "<NOT_EOL>",
    "<token of kind 4>",
    "\"MANCHE N\"",
    "\"TOUR N\"",
    "\"BILAN DES MISES\"",
    "\"\\\">Mise<\"",
    "\"\\\">Sorts<\"",
    "\"Clonage\"",
    "\"Destruction de\"",
    "\"Vol de\"",
    "\"Recyclage de\"",
    "\"clLienPartie\"",
    "\"partie.php?id=\"",
    "\"DERNIERS RESULTATS\"",
    "\"&nbsp;\"",
    "<token of kind 18>",
    "<idMise>",
    "<idJoueur>",
    "<idSort>",
    "<idClone>",
    "<idVol>",
    "<idRec>",
    "\"</tr>\"",
    "\"Vol de\"",
    "<token of kind 27>",
    "<NUM>",
  };

}
